stages:
  - init
  - plan
  - apply
  - deploy_lambda

variables:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "<YOUR_ACCESS_KEY>"
  AWS_SECRET_ACCESS_KEY: "<YOUR_SECRET_KEY>"

terraform:
  image: hashicorp/terraform:1.6.0
  before_script:
    - terraform --version
  stage: init
  script:
    - cd terraform
    - terraform init

terraform_plan:
  image: hashicorp/terraform:1.6.0
  stage: plan
  script:
    - cd terraform
    - terraform plan

terraform_apply:
  image: hashicorp/terraform:1.6.0
  stage: apply
  script:
    - cd terraform
    - terraform apply -auto-approve

deploy_lambda:
  image: python:3.13
  stage: deploy_lambda
  script:
    - cd lambda
    - zip function.zip lambda_function.py
    - aws lambda update-function-code --function-name file-processor --zip-file fileb://function.zip --region $AWS_REGION
