name: Deploy AWS Lambda with Terraform

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: "us-east-1"

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3  # Use your preferred version

      # Step 3: Zip Lambda function
      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r function.zip lambda_function.py

      # Step 4: Initialize Terraform
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      # Step 6: Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
